import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ParentModeProvider } from "@/context/ParentModeContext";
import { ThemeProvider } from "@/context/ThemeContext";
import NavMenu from "@/components/NavMenu";
import IntroductionMessageButton from "@/components/IntroductionMessageButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <ThemeProvider>
          <ParentModeProvider>
            <NavMenu />
            {children}
            <IntroductionMessageButton />
          </ParentModeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}